### ISSUE TITLE
calendarizeHandle.next: backward compatibility issue

### ISSUE THREAD

**Issue by robarov** [unionco/calendarize#12]
Using the latest version `1.2.3`
## Bug
`{{ event.calendarizeHandle.next|date('D. j F Y')  }}` now returns error   
`Object of class unionco\calendarize\models\Occurrence could not be converted to string`

## Expected
In previous version, this returned `Fr. 15 februari 2019`

## Workaround
Use `{{ event.calendarizeHandle.next.format('D. j F Y')  }}`
or  `{{ event.calendarizeHandle|date('D. j F Y')  }}`

**Comment by fvaldes33** [comment]
Missed this in my last commit. I added the toString method to the Occurrence model now. As I mentioned in issue [#13](https://github.com/unionco/calendarize/issues/13), using the date twig filter would work better than the format method to ensure localization.

Fixed in [ae68f56](https://github.com/unionco/calendarize/commit/ae68f5674bc622aaa8c8a2cf47a7fe02f40e1595)
