### ISSUE TITLE
Repeat monthly date format bug

### ISSUE THREAD

**Issue by G17creative** [unionco/calendarize#22]
Found a bug within the repeat monthly. It seems like it's using the American date format, m/d/y rather than d/m/y. Selecting a date over the 12th day in a month will cause the 'Every month on the' dropdown to display 'NaNth' and 'undefined undefined'

Selecting the date 12th April 2019, which is a Friday, populates the dropdown to display 'First Wednesday' even though it's the second Friday. It's looking at the 4th December 2019 which is the first Wednesday.

Is there a setting we can add to a config file to change the date formatting?

**Comment by fvaldes33** [comment]
Sorry for the delay. I just pushed up a commit that should fix this issue, carrying over localization from the PHP side to the JS side and leveraging Moment's localization instead of plain js date.

Commit [29f2643](https://github.com/unionco/calendarize/commit/29f2643036a31f87ee06ccc42fd853958f709671)
